#!/bin/bash

table=$(pandoc -f markdown -t html data.md | sed '/col/d;/<table>/d')

cat << EOF > index.html
<html>
<head>
    <title>DATA FISIKA ITS 2020</title>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1, user-scalable=no" />
    <link rel="stylesheet" href="assets/css/main.css" />
    <script>
        (function(document) {
            'use strict';

            var TableFilter = (function(myArray) {
                var search_input;

                function _onInputSearch(e) {
                    search_input = e.target;
                    var tables = document.getElementsByClassName(search_input.getAttribute('data-table'));
                    myArray.forEach.call(tables, function(table) {
                        myArray.forEach.call(table.tBodies, function(tbody) {
                            myArray.forEach.call(tbody.rows, function(row) {
                                var text_content = row.textContent.toLowerCase();
                                var search_val = search_input.value.toLowerCase();
                                row.style.display = text_content.indexOf(search_val) > -1 ? '' : 'none';
                            });
                        });
                    });
                }

                return {
                    init: function() {
                        var inputs = document.getElementsByClassName('search-input');
                        myArray.forEach.call(inputs, function(input) {
                            input.oninput = _onInputSearch;
                        });
                    }
                };
            })(Array.prototype);

            document.addEventListener('readystatechange', function() {
                if (document.readyState === 'complete') {
                    TableFilter.init();
                }
            });

        })(document);
    </script>
</head>

<body class="single is-preload">
        <div class="post">
            <h2>
                <span>DATA FISIKA ITS 2020</span>
                <input type="search" placeholder="Cari..."
                class="form-control search-input" data-table="table"/>
            </h2>
<table>
<colgroup>
<col style="width: 5%" />
<col style="width: 20%" />
<col style="width: 5%" />
<col style="width: 10%" />
<col style="width: 20%" />
</colgroup>
$table
        </div>
            <section id="footer">
                <p class="social">Give me a Lovely Hug - <a href="https://github.com/jhagas/">GitHub</a> - 
                <a href="https://qoto.org/@jhagas">Mastodon</a></p>
            </section>
    </div>
</body>
</html>
EOF
